# Generated by Django 5.1.4 on 2026-08-12 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LSAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.TextField(blank=True, help_text="Comma-separated or free-text description of the LSA's skills/specialties.")),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LSA Profile',
                'verbose_name_plural': 'LSA Profiles',
                'db_table': 'lsa_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='lsa_is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='booking_service.lsaprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='booking_service.parent')),
            ],
            options={
                'db_table': 'booking_requests',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status'], name='booking_status_idx'), models.Index(fields=['start_time'], name='booking_start_time_idx'), models.Index(fields=['lsa', 'start_time'], name='booking_lsa_start_idx'), models.Index(fields=['parent', 'start_time'], name='booking_parent_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_time_after_start_time')],
            },
        ),
    ]
